name: Tag & GitHub release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version
        if: github.event.pull_request.merged == true
        id: version
        run: |
          NEW_VERSION=$(node -p 'require("./package.json").version')
          echo "version=v$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create a git tag
        if: github.event.pull_request.merged == true
        run: git tag ${{ steps.version.outputs.version }} && git push --tags
